name: Release (all tags)

on:
  push:
    tags:
      - "*.*.*"
      - "*.*.*b*"

env:
  # "preprod" registry
  DOCKER_PREPROD_REPO: "nwodtuhs/exegol-preprod"
  # final "production" registry target
  DOCKER_PROD_REPO: "nwodtuhs/exegol"

jobs:
  varset:
    name: Initialize variables
    runs-on: self-hosted
    outputs:
      DOCKER_PREPROD_REPO: ${{ steps.varset.outputs.DOCKER_PREPROD_REPO }}
      DOCKER_PROD_REPO: ${{ steps.varset.outputs.DOCKER_PROD_REPO }}
    steps:
      - name: Passing workflow env vars to reusable workflows
        id: varset
        run: |
          echo "DOCKER_PREPROD_REPO=${DOCKER_PREPROD_REPO}" >> $GITHUB_OUTPUT
          echo "DOCKER_PROD_REPO=${DOCKER_PROD_REPO}" >> $GITHUB_OUTPUT
  release:
    name: Publish manifest
    needs: varset
    strategy:
      matrix:
        tag: [ full, light, ad, web, osint ]
        version: ['', "-${{ github.ref_name }}"]
    uses: ./.github/workflows/sub_release_manifest.yml
    with:
      DOCKER_PREPROD_REPO: ${{ needs.varset.outputs.DOCKER_PREPROD_REPO }}
      PREPROD_MANIFEST_LIST: ${{ needs.varset.outputs.DOCKER_PREPROD_REPO }}:${{ matrix.tag }}${{ matrix.version }}
      PROD_MANIFEST_LIST: ${{ needs.varset.outputs.DOCKER_PROD_REPO }}:${{ matrix.tag }}${{ matrix.version }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}